Book entity, repository, and service tiers have been added.
oleksandr-chernetskyi/online-book-store-springboot-app pull request #1
Opened 2023-08-29 22:48 UTC by oleksandr-chernetskyi

2023-08-30 09:44 UTC, Rommelua requested changes

2023-08-30 09:44 UTC, Rommelua commented on src/main/java/onlinebookstore/model/Book.java
> +@Data
Better do not use @Data in @Entity class

2023-08-30 09:44 UTC, Rommelua commented on src/main/java/onlinebookstore/model/Book.java
> +    private String coverImage;
add constraints

2023-09-08 14:20 UTC, sokimaaa commented on src/main/java/onlinebookstore/model/Book.java
> +    private String coverImage;
not fixed

2023-09-08 14:20 UTC, sokimaaa commented on src/main/java/onlinebookstore/model/Book.java
> +@Data
not fixed

2023-09-12 10:57 UTC, Rommelua requested changes

2023-09-12 10:57 UTC, Rommelua commented on src/main/java/onlinebookstore/model/Book.java
> +@Table(name = "books")
```suggestion
@Entity
@Getter
@Setter
@NoArgsConstructor
@Table(name = "books")
```

2023-09-12 10:57 UTC, Rommelua commented on src/main/java/onlinebookstore/model/Book.java
> +    }
you can delete get/set

2023-09-12 10:57 UTC, Rommelua commented on src/main/java/onlinebookstore/model/Book.java
> +                && Objects.equals(coverImage, book.coverImage);
No need to check all fields - we have a unique business identifier for book
```suggestion
        return  Objects.equals(isbn, book.isbn);
```

2023-09-12 10:57 UTC, Rommelua commented on src/main/java/onlinebookstore/model/Book.java
> +    public String toString() {
do you need this method?

2023-09-12 10:57 UTC, Rommelua commented on src/main/java/onlinebookstore/repository/book/specification/DescriptionSpecificationProvider.java
> +public class DescriptionSpecificationProvider implements SpecificationProvider<Book> {
delete this class. Is it possible to search by full Description?

2023-09-12 10:57 UTC, Rommelua commented on src/main/java/onlinebookstore/repository/book/specification/PriceSpecificationProvider.java
> +                .get(PRICE).in(Arrays.stream(parameters).toArray()));
price IN? It is not possible to use. You should implement a search between lower and higher boundaries for price or delete it at all

2023-09-12 10:57 UTC, Rommelua commented on src/main/java/onlinebookstore/repository/book/specification/TitleSpecificationProvider.java
> +                .get(TITLE).in(Arrays.stream(parameters).toArray()));
better have 'contains' logic for the title.
When you search "Harry Potter" you want to see all the parts. But here you will see nothing.

2023-09-16 15:53 UTC, aaananas approved these changes

2023-09-17 08:44 UTC, sokimaaa requested changes

2023-09-18 09:27 UTC, Rommelua requested changes
![image](https://github.com/oleksandr-chernetskyi/online-book-store-springboot-app/assets/20326858/0b9b558d-3409-432d-be52-fc6086f719ab)
Only code connected with this task should be in the PR. Previous tasks should already be in main branch.

2023-09-27 16:57 UTC, merged